Update azure-pipelines.yml for Azure Pipelines
UKHO/owasp-zap-ui-scan pull request #5
Opened 2019-08-28 09:23 UTC by TomGuppy

2019-08-30 07:14 UTC, dynamictulip submitted a review, later dismissed

2019-09-02 08:12 UTC, gregzealley requested changes

2019-09-02 08:12 UTC, gregzealley commented on owasp-zap-ui-scan-template.yml
> +    displayName: "Set chmod permissions (ArtifactStagingDirectory)"
Would this read better as "Set permissions on Build.ArtifactStagingDirectory" - consistent use of "Build.ArtifactStagingDirectory"in the directory names

2019-09-02 08:12 UTC, gregzealley commented on owasp-zap-ui-scan-template.yml
> +    displayName: "Publish OWASP ZAP Report"
Worth saying "HTML" report to better distinguish this from the previous one?

2019-09-02 08:12 UTC, gregzealley commented on owasp-zap-ui-scan-template.yml
> +    displayName: "Revert chmod permissions (ArtifactStagingDirectory)"
Refer to above comment (if you agree with that 😄 )

2019-09-02 08:16 UTC, gregzealley approved these changes

2019-09-02 08:17 UTC, merged